# Auto-generated by build/generate_icons.py — do not edit by hand.
#
# All condition names are aliased to the placeholder bitmap until
# real per-condition icons are designed and added to ICONS in
# build/generate_icons.py.

from . import placeholder

sunny = placeholder
cloudy = placeholder
partly_cloudy = placeholder
rain = placeholder
snow = placeholder
thunderstorm = placeholder
fog = placeholder
night = placeholder
